language: ruby
cache:
  - bundler
services:
  - postgresql
before_script:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:create
script:
  - bundle exec rspec ./spec --format documentation
